repo: https://github.com/openwrt/openwrt.git
branch: openwrt-21.02
revision: b4d7885af70a42df7577157b96f941500bd17bfb
output_dir: ./output

patch_folders:
  - patches/base
  - patches/linkease/x86_64
