---
description: Add the system base dependencies

packages:
  - cgi-io
  - liblucihttp
  - luci
  - luci-base
  - luci-compat
  - uhttpd
  - uhttpd-mod-ubus

diffconfig: |
  CONFIG_TARGET_KERNEL_PARTSIZE=128
  CONFIG_TARGET_ROOTFS_PARTSIZE=1024
